env:
  ProjectPath: src/OpenApiExtension/SwaggerExtension
  ProjectName: SwaggerExtension
  TagName: OpenApi

name: Release with Tag (OpenApi.v*.*.*) & Push Nuget

on:
  push:
    tags:
    - "OpenApi.v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Verify commit exists in origin/master
    #  run: |
    #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    #    git branch --remote --contains | grep origin/master
       
    - name: Get Version from TagName
      run: echo "VERSION=${GITHUB_REF#refs/tags/${{env.TagName}}.v}" >> $GITHUB_ENV
          
    - name: Print Version
      run: echo ${VERSION}
     
    - name: Build
      run: dotnet build --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack ${{env.ProjectPath}}/${{env.ProjectName}}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}